project:
  type: website
  resources:
    - audio
  render:
    - "*.qmd"
    - "*.ipynb"
    - "!xtra"

website:
  title: "SQL Mini Project"
  favicon: "assets/gu-logo.png"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: plots.ipynb
        text: Plot Code

format:
  html:
    theme: cosmo
    bibliography:   ./assets/references.bib
    csl:  ./assets/nature.csl
    toc: true
    embed-resourcces: true



